config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
  resource :user, only: [:show, :edit, :update, :destroy]
  resources :products, only: [:index, :show, :destroy]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :shippings, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create]
  resources :order_products, only: [:create, :update, :destroy]


  namespace :admin do
  	resources :users, only: [:index, :show, :edit, :update, :destroy]
  	resources :products
  	resources :discs, only: [:create, :update, :destroy]
  	resources :songs, only: [:create, :update, :destroy]
  	resources :orders, only: [:index, :show, :update, :destroy]
  	resources :order_products, only: [:update, :destroy]
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  belongs_to :user

  # enum order_status: { undispatched: 0, Shipped: 1 }
  enum order_status: { 未発送: 0, 発送済み: 1 }
  validates :order_name, presence: true
  validates :order_address, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_user!
  before_action :only_admin_user


  def index
  	@orders = Order.all
    @users = User.count
    # @orders.each do |order|
    #   @order_products = OrderProduct.where(order_id: order.id)
    #   @order_products.each do |p|
    #     @p = Product.find(p.product_id)
    #   end
    # end

    @order_products = OrderProduct.all
    @order_products.inject(0) { |sum, order_product|
      @sales = sum + (order_product.order_quantity*order_product.order_price)
    }
    # @sales = 0
    # @order_products.each do |order_product|
    #   @sales += (order_product.order_quantity*order_product.product.price)
    # end
  end

  def show

     @order = Order.find(params[:id])
     @order_products = OrderProduct.where(order_id: @order.id)
    #  @order_products.each do |product|
    #   @p = Product.find(product.product_id)
    # end
  end

  def update
    order = Order.find(params[:id])
    if order.update(order_params)
      redirect_to admin_order_path(order.id)
    end
  end



  private
  def only_admin_user
    if current_user.id != 1
      redirect_to products_path
    end
  end

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   PER = 3
  def index
    @order = Order.new
    @carts = current_user.carts
  end

  def create
    if current_user.shippings.present?

    	shipping = Shipping.find(params[:order][:user_id])#配送先の指定、本来は実体のないカラムを作るべき
    	@order = Order.new(user_id: shipping.user_id, order_name: shipping.shipping_name, order_address: shipping.shipping_address)#注文テーブルの作成
    	@order.save#注文テーブル保存
    	@carts = Cart.where(user_id: current_user.id)
    	@carts.each do |cart|
  	  	@order_product = OrderProduct.new(order_id:@order.id,order_quantity:cart.quantity,order_price:cart.product.price,
  	  		                                order_product_image_id:cart.product.product_image_id,order_name:cart.product.product_name,product_id:cart.product_id)
  	  	cart.product.stock_quantity -= @order_product.order_quantity#在庫数から注文数をひく
  	  	 @order_product.save#注文履歴保存

  	  	 cart.product.save
  	  	 cart.destroy#カートの削除
      end
      redirect_to user_path(current_user)
      flash[:notice] = "注文が確定しました"
    else
      redirect_to shippings_path
      # flash[:notice] = "配送先を登録して下さい"
    end
  end



end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
	<div class="container admin_orderbox">
		<div class="row">
				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h2 class="panel-title">サイト内状況</h2>
						</div>
						<div class="panel-body">
							<table class="table">
								<tr>
									<th style="width: 30%">売り上げ</th>
									<td style="width: 70%; text-align: left;"><span class="total-name">総合計:  </span><span class="total-price"><%= number_with_delimiter(@sales) %>円</span><span>  (税込)</span></td>
								</tr>
								<tr>
									<th style="width: 30%">登録者数</th>
									<td style="width: 70%; text-align: left;"><span class="total-name">総登録者数: <span class="total-price"><%= @users %>人</span></span></td>
								</tr>
							</table>
						</div>
					</div>
				</div>
			<div class="col-md-8">
				<div class="admin_order_headline"><h2>注文一覧</h2></div>
				<table class="table">
					<thead>
						<tr>
							<th class="align-middle">注文番号</th>
							<th class="align-middle">配送状況</th>
							<th class="align-middle">配送先</th>
							<th class="align-middle">購入者</th>
							<th class="align-middle">購入日時</th>
							<th class="align-middle">注文詳細</th>
						</tr>
					</thead>
					<tbody>
						<% @orders.each do |order| %>
						<tr>
							<td class="align-middle"><%= order.id %></td>
							<td class="align-middle"><%= order.order_status %></td>
							<td class="align-middle"><%= order.order_address %></td>
							<td class="align-middle">
								<% @user = User.with_deleted.find(order.user_id) %>
								<%= @user.first_name %>
							</td>
							<td class="align-middle"><%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
							<td class="align-middle"><%= link_to "詳細", admin_order_path(order.id), class: "btn btn-default" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>

app/views/admin/orders/show.html.erb
<div class="container admin_orderbox">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
      <div class="admin_order_headline">
			  <h2>注文詳細 一覧</h2>
      </div>
			<div class="row">
        <div class="col-md-5 col-md-offset-1">
          <label>注文番号</label>
          <p><%= @order.id %></p>
          <label>ステータス</label>
          <%= form_for([:admin, @order]) do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys.to_a, {} %>
            <%= f.submit '変更' %>
          <% end %>
          <label>購入者</label>
          <p><%= @order.order_name %></p>
        </div>
        <div class="col-md-5">
          <label>購入日時</label>
          <p><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
          <label>発送日時</label>
          <p><% if @order.order_status == "発送済み" %>
                <%= @order.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
              <% else %>
                未発送
              <% end %>
          </p>
          <label>配送先住所</label>
          <p><%= @order.order_address %></p>
          <div class="total-right">
            <% @order_products.inject(0) { |sum, order_product| @total = sum + (order_product.order_quantity * order_product.order_price) } %>
            <span class="total-name">総合計:  </span><span class="total-price"><%= number_with_delimiter(@total) %>円</span><span>  (税込)</span>
          </div>

        </div>
      </div>
      <div>
        <table class="table">
          <thead>
            <tr>
              <th>商品 ID</th>
              <th>商品名</th>
              <th>個数</th>
              <th>価格</th>
              <th>小計</th>
              <th>商品詳細</th>
            </tr>
          </thead>
          <tbody>
            <% @order_products.each do |p| %>
            <tr>
              <td><%= p.product_id %></td>
              <td><%= p.order_name %></td>
              <td><%= p.order_quantity %>枚</td>
              <td><%= number_with_delimiter(p.order_price) %>円</td>
              <td>
                <% @subtotal = p.order_quantity * p.order_price %>
                <%= number_with_delimiter(@subtotal) %>円
              </td>
              <td>
                <div>
                <%= link_to '詳細', admin_product_path(p.product_id), class: "btn btn-default" %>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
		</div>
	</div>
</div>