config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
  resource :user, only: [:show, :edit, :update, :destroy]
  resources :products, only: [:index, :show, :destroy]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :shippings, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create]
  resources :order_products, only: [:create, :update, :destroy]


  namespace :admin do
  	resources :users, only: [:index, :show, :edit, :update, :destroy]
  	resources :products
  	resources :discs, only: [:create, :update, :destroy]
  	resources :songs, only: [:create, :update, :destroy]
  	resources :orders, only: [:index, :show, :update, :destroy]
  	resources :order_products, only: [:update, :destroy]
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :product
	validates :quantity, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_login_user


  def index
    @carts = current_user.carts
  end

  def create
     if @cart = Cart.find_by(user_id: current_user.id, product_id: params[:cart][:product_id] ) #全く同じものを探してくれる
        @cart.quantity += params[:cart][:quantity].to_i
        @cart.save
     redirect_to carts_path
    else
     @cart = Cart.new(cart_params)
     @cart.user_id = current_user.id
  	 @cart.save
  	 redirect_to carts_path
  end
end

  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to carts_path
  end

  private
  def cart_params
    params.require(:cart).permit(:quantity, :product_id)
  end

  def authenticate_login_user
    unless :authenticate_user!
    redirect_to products_path
    flash[:notice] = "ログインして下さい"
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<div class="container">
	<div class="row">
			<div class="col-md-10 col-md-offset-1 background-off">
				<div class="cart-title">
				<p class="bottom-line"><strong>ショッピングカート一覧</strong></p>
				</div>
				<table class="table align-middle table-bordered">
					<thead>
						<tr>
							<th class="align-middle" style="width:120px">商品画像</th>
							<th class="align-middle" style="width:250px">商品名</th>
							<th class="align-middle" style="width:150px">数量</th>
							<th class="align-middle" style="width:100px">商品価格</th>
							<th class="align-middle" style="width:100px">小計</th>
							<th class="align-middle" style="width:60px">------</th>
						</tr>
					</thead>
					<tbody>
						<% @carts.each do |cart| %>
							<tr>
								<td class="align-middle"><%= attachment_image_tag(cart.product, :product_image, fallback: "noimage.png",size: '100x100') %></td>
								<td class="align-middle"><%= cart.product.product_name %></td>
									<%= form_for cart do |f| %>
								<td class="align-middle"><%= f. select :quantity, 1...(cart.product.stock_quantity + 1) %>
									<%= f.submit "更新する",class: "btn btn-default btn-xs btn-size" %></td>
									<% end %>
								<td class="align-middle"><%= number_with_delimiter(cart.product.price) %>円</td>
								<td class="align-middle"><%= number_with_delimiter(cart.product.price * cart.quantity) %>円</td>
								<td class="align-middle"><%= link_to "削除", cart_path(cart.id), method: :delete %></td>
								<% @carts.inject(0) { |sum, cart| @total = sum + (cart.product.price * cart.quantity) } %>
							</tr>
						<% end %>
					</tbody>
				</table>
				<div class="total-right">
				<span class="total-name">総合計:  </span><span class="total-price"><%= number_with_delimiter(@total) %>円</span><span>  (税込)</span>
				</div>
					<br>
					<% if @carts.empty? %>
					<p style="text-align:center; color:red;">カート内に商品がありません(>__<)</p>
					<% else %>
					<div class="actions row">
					<%= link_to "注文確認画面へ", orders_path,data: {"turbolinks" => false}, class: "btn btn-default col-md-offset-3 col-md-6" %>
					<% end %>
				</div>
				<br>
			</div>
	</div>
</div>