config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
  resource :user, only: [:show, :edit, :update, :destroy]
  resources :products, only: [:index, :show, :destroy]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :shippings, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create]
  resources :order_products, only: [:create, :update, :destroy]


  namespace :admin do
  	resources :users, only: [:index, :show, :edit, :update, :destroy]
  	resources :products
  	resources :discs, only: [:create, :update, :destroy]
  	resources :songs, only: [:create, :update, :destroy]
  	resources :orders, only: [:index, :show, :update, :destroy]
  	resources :order_products, only: [:update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :products, through: :carts
  has_many :carts
  has_many :order_products
  has_many :orders
  has_many :shippings

  acts_as_paranoid

 with_options unless: :provider do
   validates :first_name, presence: true
   validates :last_name, presence: true
   validates :first_name_kana,presence: true
   validates :last_name_kana,presence: true
   validates :postcode, presence: true
   validates :address, presence: true
 end

 def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0, 20]
     user.first_name = auth.info.name   # assuming the user model has a name
     # user.image = auth.info.image # assuming the user model has an image
     # If you are using confirmable and the provider(s) you use validate emails,
     # uncomment the line below to skip the confirmation emails.
     # user.skip_confirmation!
   end
 end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

	before_action :authenticate_user!
	before_action :only_admin_user

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@orders = Order.where(user_id: @user.id)
    # @order_product = OrderProduct.where(order_id: )
  #   @orders.each do |order|
  #     order_product = OrderProduct.where(order_id: order.id)
  #     order_product.each do |p|
  #       @p = Product.find(p.product_id)
  #     end
    # end
	end

  def edit
    @user = User.find(params[:id])
  end

	def update
		user = User.find(params[:id])
		user.update(user_params)
		if user.save
			redirect_to admin_user_path(user.id)
      flash[:notice] = "登録者情報を編集しました"
		else
			render :edit
      flash[:notice] = "入力情報に誤りがあります"
		end
	end

	def destroy
		user = User.find(params[:id])
		user.destroy
		redirect_to admin_users_path
    flash[:notice] = "登録者を削除しました"
	end


  private
  def only_admin_user
  	if current_user.id != 1
  		redirect_to products_path
  	end
  end

  def user_params
  	params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted? #新しいレコードかどうか
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  PER = 7
  def show
  	@user = current_user
    @orders = Order.page(params[:page]).per(PER)
  end

  def edit
  	@user = current_user
  end

  def update
       @user =current_user
    if @user.update(user_params)
       flash[:notice] = "登録情報を編集しました"
       redirect_to user_path
    else
       render :edit
    end
  end

  def destroy
     @user = current_user
     @user.destroy
     redirect_to root_path
  end

  private
   def user_params
      params.require(:user).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postcode,:address,:email)
   end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="admin_product_image">
<div class="container admin_userbox">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title text-center">登録者情報 編集</h2>
					</div>
					<div class="panel-body">
						<%= form_for ([:admin,@user]) do |f| %>

				    	<div class="field admin_user_edit_title">
					    	<%= f.label :名前 %>
					      <%= f.text_field :first_name, class: "first_name" %>
					      <%= f.text_field :last_name, class: "last_name" %><br>

					    	<%= f.label :フリガナ %>
					      <%= f.text_field :first_name_kana, class: "first_name_kana" %>
					      <%= f.text_field :last_name_kana, class: "first_name_kana" %><br>

					    	<%= f.label :郵便番号 %>
					      <%= f.text_field :postcode, class: "postcode" %><br>

					    	<%= f.label :住所 %>
					      <%= f.text_field :address, class: "address" %><br>

					    	<%= f.label :メールアドレス %>
					      <%= f.email_field :email, class: "email" %><br>

					    	<%= f.label :パスワード %>
					      <%= f.password_field :password, class: "password" %><br>

					    	<%= f.label :パスワード確認 %>
					      <%= f.password_field :password_confirmation, class: "password_confirmation" %>

					    	<div class="actions text-center">
					        <%= f.submit "登録", class: "btn btn-default" %>
					    		<%= link_to '削除', admin_user_path(@user.id), method: :delete, class: "btn btn-default" %>
					    	</div>
					    	<div>
					    	</div>
							</div>
					  <% end %>

						<!-- <div class="panel-footer">
						</div> -->
					</div>
				</div>

		</div>
	</div>
</div>
</div>

app/views/admin/users/index.html.erb
<div class="container admin_userbox">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="admin_user_headline">
				<h2 class="text-left">登録者 一覧</h2>
			</div>
			<table class="table">
				<thead>
					<tr>
						<th>登録者 ID</th>
						<th>名前</th>
						<th>メールアドレス</th>
						<th></th>
					</tr>
				</thead>
				<tbody class="text-left">
					<% @users.each do |user| %>
					<% next if user.id == 1 %>
					<tr>
						<td><%= user.id %></td>
						<td><%= user.first_name %><%= user.last_name %></td>
						<td><%= user.email %></td>
						<td><div><%= link_to 'ユーザー詳細&購入履歴', admin_user_path(user.id), class: "btn btn-default" %></div></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/admin/users/show.html.erb
<div class="container admin_userbox">
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">登録者 詳細情報</h2>
				</div>
				<div class="panel-body">
					<table class="table" style="table-layout: fixed;">
						<tr><th style="width:22px">登録者 ID：</th><td><%= @user.id %></td></tr>
						<tr><th style="width:22px">姓：</th><td><%= @user.first_name %></td></tr>
						<tr><th style="width:22px">名：</th><td><%= @user.last_name %></td></tr>
						<tr><th style="width:22px">郵便番号：</th><td><%= @user.postcode %></td></tr>
						<tr><th style="width:22px">住所：</th><td><%= @user.address %></td></tr>
						<tr><th style="width:22px">メールアドレス：</th><td><%= @user.email %></td></tr>
						<tr><th style="width:22px">電話番号：</th><td><%= @user.phone_number %></td></tr>
					</table>
				</div>
				<%= link_to '編集', edit_admin_user_path(@user.id),class: "btn btn-default center-block" %>
			</div>
		</div>
		<div class="col-md-8">
			<div class="admin_user_headline">
				<h2 class="text-left">購入履歴</h2>
			</div>
			<table class="table">
				<thead>
					<tr>
						<th>注文番号</th>
						<th>配送状況</th>
						<th>配送先</th>
						<th>注文詳細</th>
						<th>購入日時</th>
						<th>注文詳細</th>
					</tr>
				</thead>
				<tbody>
					<% @orders.each do |order| %>
					<tr>
						<td><%= order.id %></td>
						<td><%= order.order_status %></td>
						<td><%= order.order_address %></td>
						<!-- <td><%#= @p.product_name %></td> -->
						<td>
							<% order.order_products.each do |p| %>
								<%= p.order_name %>
							<% end %>
						</td>
						<td><%= order.created_at %></td>
						<td><%= link_to '詳細', admin_order_path(order.id), class: "btn btn-default" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>