config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
  resource :user, only: [:show, :edit, :update, :destroy]
  resources :products, only: [:index, :show, :destroy]
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :shippings, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create]
  resources :order_products, only: [:create, :update, :destroy]


  namespace :admin do
  	resources :users, only: [:index, :show, :edit, :update, :destroy]
  	resources :products
  	resources :discs, only: [:create, :update, :destroy]
  	resources :songs, only: [:create, :update, :destroy]
  	resources :orders, only: [:index, :show, :update, :destroy]
  	resources :order_products, only: [:update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  #acts_as_paranoid
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :product
	validates :quantity, presence: true
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc
	accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true
	validates :disc_name, presence: true
	validates :disc_number, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
  belongs_to :user

  # enum order_status: { undispatched: 0, Shipped: 1 }
  enum order_status: { 未発送: 0, 発送済み: 1 }
  validates :order_name, presence: true
  validates :order_address, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :order_quantity, presence: true
  validates :order_price, presence: true
  validates :order_name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :product_image
	has_many :discs, inverse_of: :product
	has_many :order_products
	has_many :orders, through: :order_products
	has_many :users, through: :carts
  	has_many :carts

	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true
	enum genre:{JPOP: 0,KPOP:1,洋楽:2,ジャズ:3,ロック:4,クラシック:5,アニメ:6,ヒップホップ:7,ソウル:8}
	validates :product_name, presence: true
	validates :artist_name, presence: true
	validates :price, presence: true
	validates :company, presence: true
	validates :stock_quantity, presence: true
	acts_as_paranoid
end

app/models/shipping.rb
class Shipping < ApplicationRecord
	belongs_to :user
	validates :shipping_address, presence: true
	validates :shipping_postcode, presence: true
	validates :shipping_name, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
	validates :title, presence: true
	validates :song_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :products, through: :carts
  has_many :carts
  has_many :order_products
  has_many :orders
  has_many :shippings

  acts_as_paranoid

 with_options unless: :provider do
   validates :first_name, presence: true
   validates :last_name, presence: true
   validates :first_name_kana,presence: true
   validates :last_name_kana,presence: true
   validates :postcode, presence: true
   validates :address, presence: true
 end

 def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0, 20]
     user.first_name = auth.info.name   # assuming the user model has a name
     # user.image = auth.info.image # assuming the user model has an image
     # If you are using confirmable and the provider(s) you use validate emails,
     # uncomment the line below to skip the confirmation emails.
     # user.skip_confirmation!
   end
 end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_login_user


  def index
    @carts = current_user.carts
  end

  def create
     if @cart = Cart.find_by(user_id: current_user.id, product_id: params[:cart][:product_id] ) #全く同じものを探してくれる
        @cart.quantity += params[:cart][:quantity].to_i
        @cart.save
     redirect_to carts_path
    else
     @cart = Cart.new(cart_params)
     @cart.user_id = current_user.id
  	 @cart.save
  	 redirect_to carts_path
  end
end

  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to carts_path
  end

  private
  def cart_params
    params.require(:cart).permit(:quantity, :product_id)
  end

  def authenticate_login_user
    unless :authenticate_user!
    redirect_to products_path
    flash[:notice] = "ログインして下さい"
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   PER = 3
  def index
    @order = Order.new
    @carts = current_user.carts
  end

  def create
    if current_user.shippings.present?

    	shipping = Shipping.find(params[:order][:user_id])#配送先の指定、本来は実体のないカラムを作るべき
    	@order = Order.new(user_id: shipping.user_id, order_name: shipping.shipping_name, order_address: shipping.shipping_address)#注文テーブルの作成
    	@order.save#注文テーブル保存
    	@carts = Cart.where(user_id: current_user.id)
    	@carts.each do |cart|
  	  	@order_product = OrderProduct.new(order_id:@order.id,order_quantity:cart.quantity,order_price:cart.product.price,
  	  		                                order_product_image_id:cart.product.product_image_id,order_name:cart.product.product_name,product_id:cart.product_id)
  	  	cart.product.stock_quantity -= @order_product.order_quantity#在庫数から注文数をひく
  	  	 @order_product.save#注文履歴保存

  	  	 cart.product.save
  	  	 cart.destroy#カートの削除
      end
      redirect_to user_path(current_user)
      flash[:notice] = "注文が確定しました"
    else
      redirect_to shippings_path
      # flash[:notice] = "配送先を登録して下さい"
    end
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
      @search = Product.page(params[:page]).ransack(params[:q])
      @products = @search.result.order(created_at: "desc")
    end

    def show
      @product = Product.find(params[:id])
      @cart = Cart.new
    end

    def new
      @products = product.new
      @user = current_user
    end

    def create
     @products = product.new
     @product.user_id = current_user
     if @product.save
      flash[:notice] = "product was successfully created."
      redirect_to admin_products_path(@product.id)
    else
      @products = Product.all
      @user = current_user
      render "index"
    end
    end

    def edit
    end

    def update
    end

    def destroy
    end
    private
  def correct_user
      product = Product.find(params[:id])

    end
  def product_params
    params.require(:product).permit(:title, :opinion, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  PER = 7
  def show
  	@user = current_user
    @orders = Order.page(params[:page]).per(PER)
  end

  def edit
  	@user = current_user
  end

  def update
       @user =current_user
    if @user.update(user_params)
       flash[:notice] = "登録情報を編集しました"
       redirect_to user_path
    else
       render :edit
    end
  end

  def destroy
     @user = current_user
     @user.destroy
     redirect_to root_path
  end

  private
   def user_params
      params.require(:user).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postcode,:address,:email)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shippings_helper.rb
module ShippingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ringo</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if user_signed_in? && current_user.id == 1 %>
  <div>
  <% else %>
  <div class="main_contents">
  <% end %>

    <header>
      <div class="head">
        <% if user_signed_in? && current_user.id == 1 %>
        <!-- 管理者がログインしている時 -->
          <%= link_to admin_orders_path do %>
              <%= image_tag "logo.png" %>
          <% end %>
          <p>管理者画面</p>
          <div class="message_notice">
          <%= flash[:notice] %>
          </div>
          <nav class="head_navi clearfix">
            <li class="navi-list"><%= link_to 'TOP画面へ戻る', products_path %></li>
            <li class="navi-list"><%= link_to '登録者 一覧', admin_users_path %></li>
            <li class="navi-list"><%= link_to '登録商品 一覧', admin_products_path %></li>
            <li class="navi-list"><%= link_to "新規商品登録", new_admin_product_path, data: {"turbolinks" => false} %></li>
            <li class="navi-list"><%= link_to 'ログアウト', destroy_user_session_path , method: :delete %></li>
          </nav>

        <% elsif user_signed_in? %>
        <!-- ユーザーがログインしている時 -->
          <%= link_to root_path do %>
              <%= image_tag "logo.png" %>
          <% end %>
          <div class="message_notice">
          <%= flash[:notice] %>
          </div>
          <nav class="head_navi clearfix">
            <li class="navi-list"><br>
              <%= link_to carts_path do %>
                <p><span class="glyphicon glyphicon-shopping-cart" style="font-size:25px;"></span>カート</p>
              <% end %></li>
            <li class="navi-list">
              <%= link_to destroy_user_session_path, method: :delete do %>
              <p><%= image_tag "icon2.png", size: "30x30" %><br>ログアウト</p>
              <% end %>
            </li>
            <li class="navi-list">
              <%= link_to user_path do %>
              <p><%= image_tag "icon1.png", size: "30x30" %><br><%= "#{current_user.first_name} 様" %></p>
              <% end %>
            </li>
          </nav>
        <% else %>
        <!-- ユーザーがログインしていない時 -->
          <%= link_to root_path do %>
              <%= image_tag "logo.png" %>
          <% end %>
          <div class="message_notice">
          <%= flash[:notice] %>
          </div>
          <nav class="head_navi clearfix">
            <li class="navi-list">
              <%= link_to new_user_registration_path,data: {"turbolinks" => false} do %>
              <p><%= image_tag "icon2.png", size: "30x30" %><br>新規会員登録</p>
              <% end %>
            </li>
            <li class="navi-list">
              <%= link_to new_user_session_path,data: {"turbolinks" => false} do %>
              <p><%= image_tag "icon2.png", size: "30x30" %><br>ログイン</p>
              <% end %>
            </li>
            <li class="navi-list">
              <a><p><%= image_tag "icon1.png", size: "30x30" %><br>ゲスト様</p></a></li>
          </nav>
        <% end %>
      </div>
    </header>

      <div class="main_contents_mask">
        <%= yield %>
      </div>
  </div>

    <footer class="footer">
      <ul class="footer_company">
        <li class="company_list"><a href="#">会社情報</a></li>
        <li class="company_list"><a href="#">お知らせ</a></li>
        <li class="company_list"><a href="#">よくあるご質問</a></li>
        <li class="company_list"><a href="#">採用情報</a></li>
        <li class="company_list"><a href="#">お問い合わせ</a></li>
      </ul>
      <div class="company_name">
        <p class="text-muted">©︎林檎team</p>
      </div>
      <p class="footer_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.<br>
      The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters</p>
    </footer>

  </body>
</html>